import type { Locale } from '@shared/types';

const en = {
  title: 'Contribute & feedback',
  subtitle: 'Share one useful thing. You can keep it short or add structured detail when it helps.',
  back: 'Back to library',
  choose: 'What would you like to do?',
  flows: {
    content: {
      title: 'Fix or add content',
      description: 'Correct something, add a missing detail, or propose new content.',
    },
    idea: {
      title: 'Suggest an improvement',
      description: 'Share an idea about Enso, its navigation, or a feature.',
    },
    bug: {
      title: 'Report a problem',
      description: 'Tell us what broke or behaved unexpectedly.',
    },
  },
  changeFlow: 'Change',
  content: {
    typeLabel: 'What kind of content?',
    types: {
      technique: 'Technique',
      exercise: 'Exercise',
      routine: 'Routine',
      form: 'Form or program',
      glossary: 'Glossary term',
      exam: 'Exam content',
      other: 'Other',
    },
    modeLabel: 'Does it already exist?',
    modes: { edit: 'Update existing', new: 'Add new' },
    existingLabel: 'Find the existing item',
    existingPlaceholders: {
      technique: 'Search techniques…',
      exercise: 'Search exercises…',
      routine: 'Search routines…',
      form: 'Search forms and programs…',
      glossary: 'Search glossary terms…',
      exam: 'Name the exam or section',
      other: 'Name the page or item',
    },
    nameLabel: 'Name',
    namePlaceholder: 'What should this be called?',
    detailsLabel: 'What should change?',
    detailsNewLabel: 'What should be added?',
    detailsPlaceholder: 'Describe the useful part in your own words. A short note is enough.',
    variantToggle: 'This is about a specific technique variation',
    variantTitle: 'Technique variation',
    direction: 'Direction',
    hanmi: 'Hanmi',
    weapon: 'Weapon',
    version: 'Trainer or version ID (optional)',
    moreTitle: 'Add structured details',
    moreDescription: 'Optional — only fill in what you know.',
    taxonomyTitle: 'Classification',
    attack: 'Attack',
    category: 'Category',
    level: 'Level',
    routineCategory: 'Routine category',
    estimatedMinutes: 'Estimated minutes',
    routineExercises: 'Exercise plan',
    routineExercisePlaceholder: 'Exercise — duration — optional cue',
    steps: 'Steps',
    addStep: 'Add step',
    uke: 'Uke guidance',
    keyPoints: 'Key points',
    mistakes: 'Common mistakes',
    addItem: 'Add item',
    context: 'Context or notes',
    attribution: 'Source, trainer, or dojo attribution',
    media: 'Reference link',
    contributor: 'Your name for credit (optional)',
    consent: 'I agree that this contribution may be reviewed and used in Enso.',
  },
  idea: {
    area: 'Area or page (optional)',
    areaPlaceholder: 'e.g. library, search, study',
    details: 'What would make Enso better?',
    detailsPlaceholder: 'Describe the improvement you have in mind.',
    media: 'Screenshot or reference link (optional)',
  },
  bug: {
    location: 'Where did it happen? (optional)',
    locationPlaceholder: 'e.g. technique page, bookmark button',
    details: 'What went wrong?',
    detailsPlaceholder: 'Tell us what you expected and what happened instead.',
    reproduction: 'Steps to reproduce (optional)',
    reproductionPlaceholder: '1. Open…\n2. Tap…\n3. See…',
    media: 'Screenshot or reference link (optional)',
  },
  review: 'Review contribution',
  reviewTitle: 'Ready to send?',
  reviewHint: 'Check the essentials. You can go back without losing anything.',
  edit: 'Keep editing',
  submit: 'Send feedback',
  sending: 'Sending…',
  successTitle: 'Thank you — your feedback was sent.',
  successBody: 'It will be reviewed before any content changes are published.',
  another: 'Send another',
  required: 'Add the highlighted information before continuing.',
  invalidUrl: 'Use a complete link beginning with http:// or https://.',
  submitError: 'Feedback could not be sent. Please try again.',
  saved: 'Draft saved on this device',
  email: 'Prefer email?',
};

const de: typeof en = {
  title: 'Beitragen & Feedback',
  subtitle:
    'Teile eine hilfreiche Information. Du kannst dich kurzfassen oder bei Bedarf Details ergänzen.',
  back: 'Zurück zur Bibliothek',
  choose: 'Was möchtest du tun?',
  flows: {
    content: {
      title: 'Inhalte korrigieren oder ergänzen',
      description: 'Korrigiere etwas, ergänze ein Detail oder schlage neue Inhalte vor.',
    },
    idea: {
      title: 'Verbesserung vorschlagen',
      description: 'Teile eine Idee zu Enso, der Navigation oder einer Funktion.',
    },
    bug: {
      title: 'Problem melden',
      description: 'Beschreibe, was nicht funktioniert oder sich unerwartet verhält.',
    },
  },
  changeFlow: 'Ändern',
  content: {
    typeLabel: 'Um welche Inhalte geht es?',
    types: {
      technique: 'Technik',
      exercise: 'Übung',
      routine: 'Routine',
      form: 'Form oder Programm',
      glossary: 'Glossarbegriff',
      exam: 'Prüfungsinhalt',
      other: 'Andere',
    },
    modeLabel: 'Gibt es den Inhalt bereits?',
    modes: { edit: 'Bestehendes aktualisieren', new: 'Neu hinzufügen' },
    existingLabel: 'Bestehenden Inhalt finden',
    existingPlaceholders: {
      technique: 'Techniken suchen…',
      exercise: 'Übungen suchen…',
      routine: 'Routinen suchen…',
      form: 'Formen und Programme suchen…',
      glossary: 'Glossarbegriffe suchen…',
      exam: 'Prüfung oder Abschnitt nennen',
      other: 'Seite oder Inhalt nennen',
    },
    nameLabel: 'Name',
    namePlaceholder: 'Wie soll der Inhalt heißen?',
    detailsLabel: 'Was soll geändert werden?',
    detailsNewLabel: 'Was soll ergänzt werden?',
    detailsPlaceholder: 'Beschreibe den hilfreichen Teil mit eigenen Worten. Eine kurze Notiz reicht.',
    variantToggle: 'Es geht um eine bestimmte Technikvariante',
    variantTitle: 'Technikvariante',
    direction: 'Richtung',
    hanmi: 'Hanmi',
    weapon: 'Waffe',
    version: 'Trainer- oder Versions-ID (optional)',
    moreTitle: 'Strukturierte Details ergänzen',
    moreDescription: 'Optional — trage nur ein, was du weißt.',
    taxonomyTitle: 'Einordnung',
    attack: 'Angriff',
    category: 'Kategorie',
    level: 'Grad',
    routineCategory: 'Routinenkategorie',
    estimatedMinutes: 'Geschätzte Minuten',
    routineExercises: 'Übungsplan',
    routineExercisePlaceholder: 'Übung — Dauer — optionaler Hinweis',
    steps: 'Schritte',
    addStep: 'Schritt hinzufügen',
    uke: 'Hinweise für Uke',
    keyPoints: 'Kernpunkte',
    mistakes: 'Häufige Fehler',
    addItem: 'Punkt hinzufügen',
    context: 'Kontext oder Notizen',
    attribution: 'Quelle, Trainer oder Dojo',
    media: 'Referenzlink',
    contributor: 'Dein Name für die Nennung (optional)',
    consent: 'Ich stimme zu, dass dieser Beitrag geprüft und in Enso verwendet werden darf.',
  },
  idea: {
    area: 'Bereich oder Seite (optional)',
    areaPlaceholder: 'z. B. Bibliothek, Suche, Lernen',
    details: 'Was würde Enso verbessern?',
    detailsPlaceholder: 'Beschreibe deine Idee.',
    media: 'Screenshot- oder Referenzlink (optional)',
  },
  bug: {
    location: 'Wo ist es passiert? (optional)',
    locationPlaceholder: 'z. B. Technikseite, Lesezeichen-Schaltfläche',
    details: 'Was ist schiefgelaufen?',
    detailsPlaceholder: 'Was hast du erwartet und was ist stattdessen passiert?',
    reproduction: 'Schritte zum Nachstellen (optional)',
    reproductionPlaceholder: '1. Öffnen…\n2. Tippen…\n3. Beobachten…',
    media: 'Screenshot- oder Referenzlink (optional)',
  },
  review: 'Beitrag prüfen',
  reviewTitle: 'Bereit zum Senden?',
  reviewHint: 'Prüfe die wichtigsten Angaben. Du kannst ohne Datenverlust zurückgehen.',
  edit: 'Weiter bearbeiten',
  submit: 'Feedback senden',
  sending: 'Wird gesendet…',
  successTitle: 'Danke — dein Feedback wurde gesendet.',
  successBody: 'Inhaltsänderungen werden vor der Veröffentlichung geprüft.',
  another: 'Weiteres Feedback senden',
  required: 'Ergänze die markierten Angaben, bevor du fortfährst.',
  invalidUrl: 'Verwende einen vollständigen Link mit http:// oder https://.',
  submitError: 'Feedback konnte nicht gesendet werden. Bitte versuche es erneut.',
  saved: 'Entwurf auf diesem Gerät gespeichert',
  email: 'Lieber per E-Mail?',
};

export const getFeedbackCopy = (locale: Locale): typeof en => (locale === 'de' ? de : en);
